### ISSUE TITLE
Add individual folder, create own space in Readme.md and add wiki page

### ISSUE THREAD

**Issue by jarugulavenkat7** [jarugulavenkat7/44-517-Sec02-03-Java#1]

**Comment by akhilkasuvojula** [comment]
I have added my folder and created my own space in Readme and added wiki page.

**Comment by jarugulavenkat7** [comment]
1) I have created a folder on my name in the repo
2) Created own space in the readme.md
3) Added wiki page to log my contribution

**Comment by ajayarram** [comment]
Added my folder and created my own space in Readme file
 Added wiki page.

**Comment by saikiranreddyenugala** [comment]
I have added my folder  and created my own space in Readme
added wiki page

**Comment by madhukonda** [comment]
I have added my folder and created my own space in Readme
added wiki page
